name: Erlang CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.2', '23.3.4.2', '22.3.4.20']
        rebar3_version: ['3.16.1']
        os: [ubuntu-18.04]
        include:
          - otp_version: '21.3.8.24'
            rebar3_version: '3.15.2'
            os: ubuntu-18.04
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
        elixir-version: '1.11.1'
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-2
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp_version }}-2-
    - name: Compile
      run: rebar3 compile
    - name: EUnit tests
      run: rebar3 eunit --cover
    - name: Common Test tests
      run: rebar3 ct --cover
    - name: PropEr tests
      run: rebar3 proper --cover
    - name: XRef
      run: rebar3 xref
    - name: Covertool
      if: ${{ always() }}
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v1
      if: ${{ always() }}
      with:
        file: _build/test/covertool/brotli.covertool.xml
        env_vars: OTP_VERSION

  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.2']
        rebar3_version: ['3.16.1']
        os: [ubuntu-18.04]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
        elixir-version: '1.11.1'
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-2
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp_version }}-2-
    - name: Erlfmt Check
      run: rebar3 fmt --check

  dialyzer:
    name: Dialyze on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.2', '23.3.4.2', '22.3.4.20']
        rebar3_version: ['3.16.1']
        os: [ubuntu-18.04]
        include:
          - otp_version: '21.3.8.24'
            rebar3_version: '3.15.2'
            os: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles('rebar.lock') }}-2
        restore-keys: |
          ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-2-
    - name: Compile
      run: rebar3 compile
    - name: Dialyzer
      run: rebar3 dialyzer
